const $=s=>document.querySelector(s);const canvas=$("#canvas"),ctx=canvas.getContext("2d");let project={name:"My Rake Game",objects:[{name:"Player",x:80,y:140,size:42,color:"#5eead4"},{name:"Goal",x:500,y:220,size:42,color:"#fbbf24"}],code:"// Add game logic here.\n// 'canvas' and 'ctx' are available.\n\nfunction update() {\n  // Example: move the player with WASD.\n}\n"};let selected=0;
function status(t){$("#status").textContent=t}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#0d1015";ctx.fillRect(0,0,canvas.width,canvas.height);project.objects.forEach((o,i)=>{ctx.fillStyle=o.color;ctx.fillRect(o.x,o.y,o.size,o.size);if(i===selected){ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.strokeRect(o.x-2,o.y-2,o.size+4,o.size+4)}})}
function renderObjects(){$("#objects").innerHTML=project.objects.map((o,i)=>'<button class="object '+(i===selected?'selected':'')+'" data-i="'+i+'">'+o.name+'</button>').join("");document.querySelectorAll(".object").forEach(b=>b.onclick=()=>{selected=+b.dataset.i;syncInspector();renderObjects();draw()})}
function syncInspector(){const o=project.objects[selected];if(!o)return;$("#name").value=o.name;$("#x").value=o.x;$("#y").value=o.y;$("#size").value=o.size;$("#color").value=o.color}
function updateObject(){const o=project.objects[selected];if(!o)return;o.name=$("#name").value;o.x=+$("#x").value;o.y=+$("#y").value;o.size=Math.max(4,+$("#size").value);o.color=$("#color").value;renderObjects();draw();status("Changed")}
["name","x","y","size","color"].forEach(id=>$("#"+id).addEventListener("input",updateObject));
$("#addBtn").onclick=()=>{project.objects.push({name:"Object "+(project.objects.length+1),x:260,y:140,size:40,color:"#a78bfa"});selected=project.objects.length-1;renderObjects();syncInspector();draw();status("Object added")};
$("#newBtn").onclick=()=>{project={name:"My Rake Game",objects:[],code:$("#code").value};selected=0;renderObjects();syncInspector();draw();status("New project")};
$("#saveBtn").onclick=()=>chrome.storage.local.set({rakeProject:project},()=>status("Saved locally"));
chrome.storage.local.get({rakeProject:null},d=>{if(d.rakeProject)project=d.rakeProject;$("#code").value=project.code;renderObjects();syncInspector();draw()});
$("#code").addEventListener("input",()=>project.code=$("#code").value);
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab).classList.add("active");if(b.dataset.tab==="preview")run()});
function gameHtml(){const data=JSON.stringify(project.objects);const code=project.code.replace(/<\\/script/gi,"<\\\\/script");return '<!doctype html><html><body style="margin:0;background:#0d1015;display:grid;place-items:center;height:100vh"><canvas id="game" width="640" height="360"></canvas><script>const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),objects='+data+';function draw(){ctx.fillStyle="#0d1015";ctx.fillRect(0,0,640,360);objects.forEach(o=>{ctx.fillStyle=o.color;ctx.fillRect(o.x,o.y,o.size,o.size)})}'+code+';draw();update?.();<\\/script></body></html>'}
function run(){$("#previewFrame").srcdoc=gameHtml();status("Preview running")}
$("#runBtn").onclick=run;$("#exportBtn").onclick=()=>{const blob=new Blob([gameHtml()],{type:"text/html"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=(project.name||"rake-game").replace(/[^a-z0-9-_]+/gi,"-").toLowerCase()+".html";a.click();URL.revokeObjectURL(a.href);status("Game exported")};
$("#code").value=project.code;renderObjects();syncInspector();draw();